-- ============================================================
-- EDMS - SINGLE DATABASE MIGRATION
-- PostgreSQL / Neon compatible
--
-- Run after the application has created the base tables, or run
-- against an existing EDMS PostgreSQL database.
-- This file combines the old role, document, and storage migrations.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- USERS: storage + registration terms
-- ------------------------------------------------------------

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS storage_limit_bytes BIGINT NOT NULL DEFAULT 2147483648;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS storage_limit_gb NUMERIC(10,2) NOT NULL DEFAULT 2;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS terms_accepted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMP NULL;

-- Existing non-admin accounts become active employees.
UPDATE users
SET
    role = 'employee',
    status = 'active',
    is_active = TRUE
WHERE role IS NULL OR role NOT IN ('admin', 'pending', 'rejected', 'employee', 'readonlyemployee');

-- Existing employees receive 2 GB.
UPDATE users
SET
    storage_limit_gb = 2,
    storage_limit_bytes = 2147483648
WHERE role = 'employee';

-- Read-only employees have no personal storage.
UPDATE users
SET
    storage_limit_gb = 0,
    storage_limit_bytes = 0
WHERE role = 'readonlyemployee';

-- Admins do not use employee storage.
UPDATE users
SET
    storage_limit_gb = 0,
    storage_limit_bytes = 0
WHERE role = 'admin';

-- ------------------------------------------------------------
-- DOCUMENTS: current document fields
-- ------------------------------------------------------------

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'pending';

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

-- ------------------------------------------------------------
-- STORAGE REQUESTS
-- Final schema:
-- id, employee_id, status, admin_note, created_at,
-- requested_gb, decided_at
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS storage_requests (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    admin_note VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    requested_gb NUMERIC(10,2) NOT NULL DEFAULT 0,
    decided_at TIMESTAMP NULL
);

ALTER TABLE storage_requests
    ADD COLUMN IF NOT EXISTS requested_gb NUMERIC(10,2) NOT NULL DEFAULT 0;

ALTER TABLE storage_requests
    ADD COLUMN IF NOT EXISTS decided_at TIMESTAMP NULL;

ALTER TABLE storage_requests
    ADD COLUMN IF NOT EXISTS admin_note VARCHAR(500);

-- Remove obsolete columns from older EDMS versions.
ALTER TABLE storage_requests DROP COLUMN IF EXISTS current_limit;
ALTER TABLE storage_requests DROP COLUMN IF EXISTS requested_limit;
ALTER TABLE storage_requests DROP COLUMN IF EXISTS reason;
ALTER TABLE storage_requests DROP COLUMN IF EXISTS processed_at;





ALTER TABLE documents
    ALTER COLUMN file_type TYPE VARCHAR(255);

ALTER TABLE admin_documents
    ALTER COLUMN file_type TYPE VARCHAR(255);

-- ------------------------------------------------------------
-- DOCUMENTS: ZIP extraction + public share links
-- ------------------------------------------------------------

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS is_archive BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS extracted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS parent_document_id INTEGER NULL
        REFERENCES documents(id)
        ON DELETE CASCADE;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS share_token VARCHAR(128);

-- Existing document links are generated by the application on startup.
CREATE UNIQUE INDEX IF NOT EXISTS ix_documents_share_token
    ON documents(share_token);

-- ------------------------------------------------------------
-- ADMIN DOCUMENTS: ZIP extraction + public share links
-- ------------------------------------------------------------

ALTER TABLE admin_documents
    ADD COLUMN IF NOT EXISTS is_archive BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE admin_documents
    ADD COLUMN IF NOT EXISTS extracted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE admin_documents
    ADD COLUMN IF NOT EXISTS parent_document_id INTEGER NULL
        REFERENCES admin_documents(id)
        ON DELETE CASCADE;

ALTER TABLE admin_documents
    ADD COLUMN IF NOT EXISTS share_token VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS ix_admin_documents_share_token
    ON admin_documents(share_token);

-- ------------------------------------------------------------
-- VERIFICATION
-- ------------------------------------------------------------

COMMIT;

SELECT id, full_name, email, role, status, is_active,
       storage_limit_gb, storage_limit_bytes
FROM users
ORDER BY id;

SELECT *
FROM storage_requests
ORDER BY id;

SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'documents'
ORDER BY ordinal_position;

SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'storage_requests'
ORDER BY ordinal_position;
